name: Manual WDIO Login

on:
  workflow_dispatch:
    inputs:
      wdioTag:
        description: 'WDIO Tag to run'
        required: false
        default: '@Login'
      additionalParams:
        description: 'Additional parameters for WDIO command'
        required: false
        default: ''

jobs:
  run-wdio-login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Run WDIO for @Login
        env:
          LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
          # Set Chrome options to fix user-data-dir issue
          WDIO_CHROME_ARGS: "--no-sandbox --disable-dev-shm-usage --disable-gpu --disable-extensions --headless --window-size=1920,1080 --user-data-dir=/tmp/chrome-data-${{ github.run_id }}-${{ github.run_attempt }}"
        run: |
          # Create a unique Chrome user data directory
          mkdir -p /tmp/chrome-data-${{ github.run_id }}-${{ github.run_attempt }}
          
          if [ -n "${{ github.event.inputs.additionalParams }}" ]; then
            npm run wdio "${{ github.event.inputs.wdioTag }}" -- ${{ github.event.inputs.additionalParams }}
          else
            npm run wdio "${{ github.event.inputs.wdioTag }}"
          fi
          
      - name: Generate and Display Test Report
        if: always()
        run: |
          echo "Generating Allure report..."
          npm run report
          
          echo "\n=================== TEST SUMMARY ===================\n"
          
          # Display test stats from the report if available
          if [ -f "allure-report/widgets/summary.json" ]; then
            echo "Test Summary Stats:"
            cat allure-report/widgets/summary.json | grep -v "uid"
            echo "\n"
          fi
          
          # Display test status breakdown if available
          if [ -f "allure-report/widgets/status-chart.json" ]; then
            echo "Test Status Breakdown:"
            cat allure-report/widgets/status-chart.json
            echo "\n"
          fi
          
          # Display test duration stats if available
          if [ -f "allure-report/widgets/duration-trend.json" ]; then
            echo "Test Duration Stats:"
            cat allure-report/widgets/duration-trend.json
            echo "\n"
          fi
          
          echo "=================== END SUMMARY ===================\n"
